# Ignore everything by default
*

# Allow sources
!src/
!src/**

# Allow compiled JAR
!build/libs/*.jar

# Allow Gradle wrapper + build scripts
!gradlew
!gradlew.bat

# IMPORTANT: allow directories (parents) explicitly
!gradle/
!gradle/wrapper/

# Allow gradle build files
!**/*.gradle
!**/*.gradle.kts
!**/gradle.properties
!settings.gradle
!settings.gradle.kts
!build.gradle
!build.gradle.kts