spring:
  autoconfigure:
    exclude:
      - org.telegram.telegrambots.webhook.starter.TelegramBotStarterConfiguration

telegram:
  bot:
    api-url: ${TELEGRAM_API_URL:}

admin:
  services:
    - name: telegram-bot
      actuator-url: http://localhost:${SERVER_PORT:8080}
    - name: journal-service
      actuator-url: http://localhost:8085