spring:
  application:
    name: it-top-ai-telegram-bot

  config:
    import: optional:file:.env[.properties]

  threads:
    virtual:
      enabled: true

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME}
    webhook:
      host: ${TELEGRAM_WEBHOOK_HOST}
      path: webhook
      secret-token: ${TELEGRAM_WEBHOOK_SECRET_TOKEN}

backend:
  base-url: ${BACKEND_BASE_URL}

proxy:
  host: ${PROXY_HOST:}
  port: ${PROXY_PORT:0}

server:
  port: ${SERVER_PORT:8080}

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
